# 파일 업로드시의 파일 경로
file:
  directory: /home/download

spring:
  #데이터베이스 연결 설정
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_second_2
    username: even_second_2
    password: zeon